//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Конверт.
    /// </summary>
    // *** Start programmer edit section *** (Конверт CustomAttributes)

    // *** End programmer edit section *** (Конверт CustomAttributes)
    [AutoAltered()]
    [Caption("Конвертация")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонвертE", new string[] {
            "ЗагрФайла.ЭксФайлы.Имя as \'Имя\'",
            "ЗагрФайла as \'Путь файла\'",
            "ВидДок as \'Вид документа\'",
            "ИмяДок as \'Имя документа\'",
            "ЗагрФайла.ПутьФайла as \'Путь файла\'",
            "ВидДок.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ЗагрФайла.ПутьФайла",
            "ВидДок.Наименование"})]
    [MasterViewDefineAttribute("КонвертE", "ЗагрФайла", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПутьФайла")]
    [MasterViewDefineAttribute("КонвертE", "ВидДок", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("КонвертL", new string[] {
            "ЗагрФайла.ЭксФайлы.Имя as \'Имя\'",
            "ЗагрФайла.ПутьФайла as \'Путь файла\'",
            "ВидДок.Наименование as \'Вид документа\'",
            "ИмяДок as \'Имя документа\'"})]
    public class Конверт : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмяДок;
        
        private IIS.Kurs2.ЗагрФайла fЗагрФайла;
        
        private IIS.Kurs2.ВидДок fВидДок;
        
        // *** Start programmer edit section *** (Конверт CustomMembers)

        // *** End programmer edit section *** (Конверт CustomMembers)

        
        /// <summary>
        /// ИмяДок.
        /// </summary>
        // *** Start programmer edit section *** (Конверт.ИмяДок CustomAttributes)

        // *** End programmer edit section *** (Конверт.ИмяДок CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяДок
        {
            get
            {
                // *** Start programmer edit section *** (Конверт.ИмяДок Get start)

                // *** End programmer edit section *** (Конверт.ИмяДок Get start)
                string result = this.fИмяДок;
                // *** Start programmer edit section *** (Конверт.ИмяДок Get end)

                // *** End programmer edit section *** (Конверт.ИмяДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Конверт.ИмяДок Set start)

                // *** End programmer edit section *** (Конверт.ИмяДок Set start)
                this.fИмяДок = value;
                // *** Start programmer edit section *** (Конверт.ИмяДок Set end)

                // *** End programmer edit section *** (Конверт.ИмяДок Set end)
            }
        }
        
        /// <summary>
        /// Конверт.
        /// </summary>
        // *** Start programmer edit section *** (Конверт.ВидДок CustomAttributes)

        // *** End programmer edit section *** (Конверт.ВидДок CustomAttributes)
        [PropertyStorage(new string[] {
                "ВидДок"})]
        [NotNull()]
        public virtual IIS.Kurs2.ВидДок ВидДок
        {
            get
            {
                // *** Start programmer edit section *** (Конверт.ВидДок Get start)

                // *** End programmer edit section *** (Конверт.ВидДок Get start)
                IIS.Kurs2.ВидДок result = this.fВидДок;
                // *** Start programmer edit section *** (Конверт.ВидДок Get end)

                // *** End programmer edit section *** (Конверт.ВидДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Конверт.ВидДок Set start)

                // *** End programmer edit section *** (Конверт.ВидДок Set start)
                this.fВидДок = value;
                // *** Start programmer edit section *** (Конверт.ВидДок Set end)

                // *** End programmer edit section *** (Конверт.ВидДок Set end)
            }
        }
        
        /// <summary>
        /// Конверт.
        /// </summary>
        // *** Start programmer edit section *** (Конверт.ЗагрФайла CustomAttributes)

        // *** End programmer edit section *** (Конверт.ЗагрФайла CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗагрФайла"})]
        [NotNull()]
        public virtual IIS.Kurs2.ЗагрФайла ЗагрФайла
        {
            get
            {
                // *** Start programmer edit section *** (Конверт.ЗагрФайла Get start)

                // *** End programmer edit section *** (Конверт.ЗагрФайла Get start)
                IIS.Kurs2.ЗагрФайла result = this.fЗагрФайла;
                // *** Start programmer edit section *** (Конверт.ЗагрФайла Get end)

                // *** End programmer edit section *** (Конверт.ЗагрФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Конверт.ЗагрФайла Set start)

                // *** End programmer edit section *** (Конверт.ЗагрФайла Set start)
                this.fЗагрФайла = value;
                // *** Start programmer edit section *** (Конверт.ЗагрФайла Set end)

                // *** End programmer edit section *** (Конверт.ЗагрФайла Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонвертE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонвертE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонвертE", typeof(IIS.Kurs2.Конверт));
                }
            }
            
            /// <summary>
            /// "КонвертL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонвертL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонвертL", typeof(IIS.Kurs2.Конверт));
                }
            }
        }
    }
}
